[package]
name = "box2d"
version = "0.0.2"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>"]
repository = "https://github.com/mattnenterprise/rust-box2d"
description = "Port of Box2d to Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dev-dependencies]
sfml = "*"
time = "*"
